name: afl3_depd
description: "A simple Flutter application to calculate shipping costs using RajaOngkir API."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  double_back_to_close: ^2.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  equatable: ^2.0.5
  fluttertoast: ^8.2.8
  provider: ^6.0.5
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

